#!/usr/bin/env sh

remote="$1"

echo ""
echo "📦 Commits que se van a subir a $remote:"
echo ""

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
    continue
  fi
  if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
    git log --pretty=format:"  - %h %s" "$local_sha" | head -20
  else
    git log --pretty=format:"  - %h %s" "$remote_sha..$local_sha"
  fi
done

echo ""
echo ""